# execfile('bot_moto_01.py')
# execfile('bot_moto_01_write.py')
# browser.quit()
# execfile('bot_moto_02.py')
# execfile('bot_moto_02_write.py')
# browser.quit()
execfile('bot_moto_03.py')
execfile('bot_moto_03_write.py')
browser.quit()
# execfile('bot_moto_04.py')
# execfile('bot_moto_04_write.py')
# browser.quit()
# execfile('bot_moto_05.py')
# execfile('bot_moto_05_write.py')
# browser.quit()
# execfile('bot_moto_06.py')
# execfile('bot_moto_06_write.py')
# browser.quit()
# execfile('bot_moto_07.py')
# execfile('bot_moto_07_write.py')
# browser.quit()
# execfile('bot_moto_09.py')
# execfile('bot_moto_09_write.py')
# browser.quit()
# execfile('bot_moto_10.py')
# execfile('bot_moto_10_write.py')
# browser.quit()
# execfile('bot_moto_11.py')
# execfile('bot_moto_11_write.py')
# browser.quit()
# execfile('bot_moto_12.py')
# execfile('bot_moto_12_write.py')
# browser.quit()
